- hosts: localhost
  tasks:
    - name: Load Storage System Vars
      include_vars: 'properties/storage_system_properties.yml'

    - name: Create CPG ansible_auto_CreateCPG-001
      hpe3par_cpg:
        storage_system_ip="{{ storage_system_ip }}"
        storage_system_username="{{ storage_system_username }}"
        storage_system_password="{{ storage_system_password }}"
        state=present_arcus
        cpg_name=ansible_auto_CreateCPG-001
        sdgs=8
        sdgw=52

    - name: Delete CPG ansible_auto_CreateCPG-001
      hpe3par_cpg:
        storage_system_ip="{{ storage_system_ip }}"
        storage_system_username="{{ storage_system_username }}"
        storage_system_password="{{ storage_system_password }}"
        state=absent
        cpg_name=ansible_auto_CreateCPG-001
