- hosts: localhost
  tasks:
    - name: Load Storage System Vars
      include_vars: 'properties/storage_system_properties.yml'

    - name: Load Volume Vars
      include_vars: 'properties/volume_properties.yml'

    - name: Get All Volumes
      hpe3par_volume_facts: 
        storage_system_ip: "{{ storage_system_ip }}"
        storage_system_username: "{{ storage_system_username }}"
        storage_system_password: "{{ storage_system_password }}"

    - name: Get Volume By Name
      hpe3par_volume_facts: 
        storage_system_ip: "{{ storage_system_ip }}"
        storage_system_username: "{{ storage_system_username }}"
        storage_system_password: "{{ storage_system_password }}"
        volume_name: "{{ volume_name }}"