- hosts: localhost
  tasks:
  - name: Load Storage System Vars
    include_vars: 'properties/storage_system_properties.yml'

  - name: Create volume on source
    hpe3par_volume:
      storage_system_ip: 10.10.10.1
      storage_system_password: password
      storage_system_username: username
      state: present
      volume_name: demo_volume_1
      size: 1024
      size_unit: MiB
      cpg: FC_r1
      snap_cpg: FC_r1

  - name: Create volume on source
    hpe3par_volume:
      storage_system_ip: 10.10.10.1
      storage_system_password: password
      storage_system_username: username
      state: present
      volume_name: demo_volume_2
      size: 1024
      size_unit: MiB
      cpg: FC_r1
      snap_cpg: FC_r1     

  - name: Create volume on target
    hpe3par_volume:
      storage_system_ip: 10.10.10.1
      storage_system_password: password
      storage_system_username: username
      state: present
      volume_name: demo_volume_1
      size: 1024
      size_unit: MiB
      cpg: FC_r1
      snap_cpg: FC_r1     

  - name: Create volume on target
    hpe3par_volume:
      storage_system_ip: 10.10.10.1
      storage_system_password: password
      storage_system_username: username
      state: present
      volume_name: demo_volume_2
      size: 1024
      size_unit: MiB
      cpg: FC_r1
      snap_cpg: FC_r1           
  
  - name: Create Remote Copy Group farhan_rcg
    hpe3par_remote_copy:
      storage_system_ip: 10.10.10.1
      storage_system_password: password
      storage_system_username: username
      state: present 
      remote_copy_group_name: farhan_rcg
      targets:
      - targetName: CSSOS-SSA06
        mode: 1
        
  - pause:
      prompt: "Press Enter"
        
  - name: Add volume to remote copy group
    hpe3par_remote_copy:
      storage_system_ip: 10.10.10.1
      storage_system_password: password
      storage_system_username: username
      state: add_volume
      remote_copy_group_name: farhan_rcg
      volume_name: demo_volume_1
      targets:
      - targetName: CSSOS-SSA06
        secVolumeName: demo_volume_1
        
  - name: Add volume to remote copy group
    hpe3par_remote_copy:
      storage_system_ip: 10.10.10.1
      storage_system_password: password
      storage_system_username: username
      state: add_volume
      remote_copy_group_name: farhan_rcg
      volume_name: demo_volume_2
      targets:
      - targetName: CSSOS-SSA06
        secVolumeName: demo_volume_2
        
  - pause:
      prompt: "Press Enter"
        
  - name: Start remote copy
    hpe3par_remote_copy:
      storage_system_ip: 10.10.10.1
      storage_system_password: password
      storage_system_username: username
      remote_copy_group_name: farhan_rcg
      state: start
      
  - pause:
      prompt: "Press Enter"
      
  - name: Stop remote copy
    hpe3par_remote_copy:
      storage_system_ip: 10.10.10.1
      storage_system_password: password
      storage_system_username: username
      remote_copy_group_name: farhan_rcg
      state: stop
      
  - pause:
      prompt: "Press Enter"
      
  - name: Remove volume from remote copy group
    hpe3par_remote_copy:
      storage_system_ip: 10.10.10.1
      storage_system_password: password
      storage_system_username: username
      state: remove_volume
      remote_copy_group_name: farhan_rcg
      volume_name: demo_volume_1
      targets:
      - targetName: CSSOS-SSA06
        secVolumeName: demo_volume_1
        
  - name: Remove volume from remote copy group
    hpe3par_remote_copy:
      storage_system_ip: 10.10.10.1
      storage_system_password: password
      storage_system_username: username
      state: remove_volume
      remote_copy_group_name: farhan_rcg
      volume_name: demo_volume_2
      targets:
      - targetName: CSSOS-SSA06
        secVolumeName: demo_volume_2
        
  - pause:
      prompt: "Press Enter"
        
  - name: Remove Remote Copy Group farhan_rcg
    hpe3par_remote_copy:
      storage_system_ip: 10.10.10.1
      storage_system_password: password
      storage_system_username: username
      state: absent 
      remote_copy_group_name: farhan_rcg

  - pause:
      prompt: "Press Enter"

  - name: dismiss remote copy link
    hpe3par_remote_copy:
      storage_system_ip: 10.10.10.1
      storage_system_password: password
      storage_system_username: username
      state: dismisslink
      target_name: CSSOS-SSA06
      source_port: 0:3:1
      target_port_wwn_or_ip: 192.168.1.2

  - name: dismiss remote copy link
    hpe3par_remote_copy:
      storage_system_ip: 10.10.10.1
      storage_system_password: password
      storage_system_username: username
      state: dismisslink
      target_name: CSSOS-SSA06
      source_port: "1:3:1"
      target_port_wwn_or_ip: 192.168.2.2

  - pause:
      prompt: "Press Enter"

  - name: Admit remote copy link
    hpe3par_remote_copy:
      storage_system_ip: 10.10.10.1
      storage_system_password: password
      storage_system_username: username
      state: admitlink
      target_name: CSSOS-SSA06
      source_port: 0:3:1
      target_port_wwn_or_ip: 192.168.1.2

  - name: Admit remote copy link
    hpe3par_remote_copy:
      storage_system_ip: 10.10.10.1
      storage_system_password: password
      storage_system_username: username
      state: admitlink
      target_name: CSSOS-SSA06
      source_port: "1:3:1"
      target_port_wwn_or_ip: 192.168.2.2

  - pause:
      prompt: "Press Enter"

  - name: start remote copy service
    hpe3par_remote_copy:
      storage_system_ip: 10.10.10.1
      storage_system_password: password
      storage_system_username: username
      state: startrcopy
