- hosts: localhost
  environment:
    http_proxy: http://web-proxy.in.hpecorp.net:8080
    http_proxy: http://web-proxy.in.hpecorp.net:8080
    no_proxy: 192.168.67.7,192.168.67.5
  
  tasks:
  
  - name: Create Schedule on source
    hpe3par_snapshot:
      storage_system_ip: 192.168.67.7
      storage_system_password: 3pardata
      storage_system_username: 3paradm
      state: create_schedule
      schedule_name: my_ansible_sc
      snapshot_name: snap-
      base_volume_name: volume_ansible_a 
      read_only: True
      expiration_time: 3
      retention_time: 3
      expiration_unit: Hours 
      retention_unit: Hours
      task_freq_custom: "0 * * * *"


  - name: Delete Schedule from source
    hpe3par_snapshot:
      storage_system_ip: 192.168.67.7
      storage_system_password: 3pardata
      storage_system_username: 3paradm
      state: delete_schedule
      schedule_name: my_ansible_sc

        
