- import_playbook: setup_vlun.yml

- hosts: localhost
  tasks:

    - name: Load VLUN Vars
      include_vars: 'properties/vlun_properties.yml'

    - name: Create VLUN
      hpe3par_vlun:
        storage_system_ip="{{ storage_system_ip }}"
        storage_system_username="{{ storage_system_username }}"
        storage_system_password="{{ storage_system_password }}"
        state=export_volume_to_hostset
        volume_name="{{ vlun_volume_name }}"
        host_set_name="{{ hostset_name }}"
        lunid=110
        autolun=false

    - name: Delete VLUN
      hpe3par_vlun:
        storage_system_ip="{{ storage_system_ip }}"
        storage_system_username="{{ storage_system_username }}"
        storage_system_password="{{ storage_system_password }}"
        state=unexport_volume_from_hostset
        volume_name="{{ vlun_volume_name }}"
        host_set_name="{{ hostset_name }}"
        autolun=false
        lunid=110

- import_playbook: cleanup_vlun.yml
