storage_system_ip: "10.132.239.118"
storage_system_username: "3paradm"
storage_system_password: "3pardata"
# ip2 and target_name are for remote_copy functionality.
storage_system_ip2: "10.132.239.130"
target_name: "s042N-FC"
